name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger deployment on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        run: |
          git config --local user.email "kyriakidis.demetrios@gmail.com"
          git config --local user.name "kyriakidisdimitrios"

          # Initialize git if not already done
          git init

          # Create gh-pages branch if it doesn't exist
          if ! git show-ref --verify --quiet refs/heads/gh-pages; then
            git checkout --orphan gh-pages
          else
            git checkout gh-pages
          fi

          # Delete all existing files except .gitignore (if needed)
          git rm -rf .

          # Copy build files from main branch
          mv ../build/* .
          rm -rf ../build

          # Commit and push changes
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push origin gh-pages --force

        env:
          CI: true  # Ensures Create React App picks up CI environment
