name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Trigger deployment on push to master branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Copy Build to gh-pages Branch
        run: |
          git config --local user.email "kyriakidis.demetrios@gmail.com"
          git config --local user.name "kyriakidisdimitrios"

          # Ensure gh-pages branch exists or create a new orphan branch
          if ! git show-ref --verify --quiet refs/heads/gh-pages; then
            git checkout --orphan gh-pages
          else
            git checkout gh-pages
          fi

          # Remove all existing files from gh-pages branch except .gitignore (if needed)
          git rm -rf .

          # Copy build output from main branch
          git checkout main -- build
          mv build/* .
          rm -rf build

          # Commit changes
          git add .
          git commit -m "Deploy to GitHub Pages"

          # Force push to gh-pages branch
          git push origin gh-pages --force

        env:
          CI: true  # Ensures Create React App picks up CI environment
